# NVIDIA Brev Deployment Configuration for SolnAI Agents
# Optimized for GPU acceleration

services:
  base-python:
    build:
      context: ./base_python_docker
      dockerfile: Dockerfile
    image: solnai/base-python:latest
    runtime: nvidia

  archon:
    build:
      context: ./Archon
      dockerfile: Dockerfile
    image: solnai/archon:latest
    environment:
      API_KEY: your_api_key_here
      API_PORT: 8000
      API_HOST: 0.0.0.0
      GPU_MEMORY_FRACTION: 0.8
      CUDA_VISIBLE_DEVICES: 0
      LOG_LEVEL: INFO
      MODEL_PATH: /path/to/model
      MAX_TOKENS: 1024
    ports:
      - "8001:8000"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - agent_network
    runtime: nvidia
    restart: unless-stopped

  tinydm-agent:
    build:
      context: ./TinyDM-agent
      dockerfile: Dockerfile
    image: solnai/tinydm-agent:latest
    environment:
      API_KEY: your_api_key_here
      API_PORT: 8000
      API_HOST: 0.0.0.0
      GPU_MEMORY_FRACTION: 0.9
      CUDA_VISIBLE_DEVICES: 1
      LOG_LEVEL: INFO
      MODEL_PATH: /path/to/tinydm/model
      MAX_TOKENS: 2048
      TEMPERATURE: 0.7
    ports:
      - "8002:8000"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 2G
        reservations:
          cpus: "0.25"
          memory: 1G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - agent_network
    runtime: nvidia
    restart: unless-stopped

  ask-reddit-agent:
    build:
      context: ./ask-reddit-agent
      dockerfile: Dockerfile
    image: solnai/ask-reddit-agent:latest
    environment:
      API_KEY: your_api_key_here
      API_PORT: 8000
      API_HOST: 0.0.0.0
      GPU_MEMORY_FRACTION: 0.9
      CUDA_VISIBLE_DEVICES: 2
      LOG_LEVEL: INFO
      MODEL_PATH: /path/to/reddit/model
      MAX_TOKENS: 2048
      TEMPERATURE: 0.8
      REDDIT_CLIENT_ID: your_reddit_client_id
      REDDIT_CLIENT_SECRET: your_reddit_client_secret
      REDDIT_USER_AGENT: your_user_agent
    ports:
      - "8003:8000"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 2G
        reservations:
          cpus: "0.25"
          memory: 1G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - agent_network
    runtime: nvidia
    restart: unless-stopped

networks:
  agent_network:
    driver: bridge

volumes:
  postgres_data: {}
